version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: xzity
      POSTGRES_PASSWORD: xzity
      POSTGRES_DB: xzity
    ports:
      - "5432:5432"
    volumes:
      - ./backend/prisma/data:/var/lib/postgresql/data
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://xzity:xzity@db:5432/xzity
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public