/*
  Warnings:

  - The values [GARDENER,PLUMBER,ELECTRICIAN,ERRAND_RUNNER,BABYSITTER,LAUNDRY,PAINTER,PHYSIOTHERAPIST,ELDER_CARE,CARPENTER,HANDYMAN,ROOFER,FENCER] on the enum `Role` will be removed. If these variants are still used in the database, this will fail.
  - The values [HAIR_DRESSER,CLEANER,GARDENER,INSTITUTE,TUTOR,HANDYMAN] on the enum `VehicleType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Role_new" AS ENUM ('ADMIN', 'CUSTOMER', 'DRIVER', 'SHOPPER', 'CLEANER', 'HAIR_DRESSER', 'BEAUTY', 'INSTITUTE', 'ENGINEERING', 'HUMAN_CARE', 'LIFESTYLE', 'IT_SERVICE', 'LEGAL_SERVICE', 'PROPERTY_CARE', 'TUTOR', 'PET_CARE', 'REALTOR', 'JOB1', 'JOB2', 'JOB3', 'JOB4');
ALTER TABLE "ServiceSubTypeRole" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING ("role"::text::"Role_new");
ALTER TYPE "Role" RENAME TO "Role_old";
ALTER TYPE "Role_new" RENAME TO "Role";
DROP TYPE "public"."Role_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "VehicleType_new" AS ENUM ('CAR', 'DELIVERY', 'TUKTUK', 'LIMO', 'TRUCK', 'WATER_TRUCK', 'TOW_TRUCK', 'WHEELCHAIR', 'PRIVATE_DRIVER', 'SHOPPER', 'HOME_CLEANING', 'BUSINESS_CLEANING', 'WINDOWS_CLEANING', 'VEHICLE_CLEANING', 'CARPET_CLEANING', 'LAUNDRY', 'MALE_HAIR_DRESSER', 'FEMALE_HAIR_DRESSER', 'MAKEUP', 'FACIAL', 'NAILS', 'EYELASH', 'BROWS', 'WAXING', 'SKIN_CARE', 'CIVIL', 'ARCHITECT', 'INTERIOR', 'MECHANICAL', 'ELECTRICAL', 'SURVEY', 'ENVIRONMENTAL', 'INDUSTRIAL', 'CONSULTANT', 'BABYSITTER', 'ELDER_CARE', 'PHYSIOTHERAPIST', 'MASSAGE', 'TRAINER', 'SPIRITUAL_ADVISOR', 'NUTRITION_DIET', 'COUNSELING', 'EVENT_PLANNER', 'PHOTOGRAPHY', 'DJ_MUSIC', 'WEB_DESIGN', 'SOCIAL_MEDIA', 'SOFTWARE', 'APP_DESIGN', 'GRAPHIC_DESIGN', 'SEO_MARKETING', 'ERRAND_RUNNER', 'ACCOUNTING', 'DOCUMENT_AUTHENTICATION', 'TAX_FILING', 'NOTARY_PAPERWORK', 'CARPENTER', 'PLUMBER', 'ELECTRICIAN', 'INSULATION', 'WATER_PROOFING', 'PAINTER', 'ROOFER', 'DECORATOR', 'LANDSCAPER', 'GARDNER', 'PEST_CONTROL', 'FENCER', 'FLOORING', 'MATH', 'SCIENCE', 'PHYSICS', 'CHEMISTRY', 'HISTORY', 'GEOGRAPHY', 'CODING', 'LANGUAGE', 'GRAMMER', 'ART', 'MUSIC', 'PET_SITTING', 'PET_BATHING', 'PET_WALKING', 'PET_TRAINING', 'PET_HAIR_CUTTING', 'PET_NAIL_CLIPPING', 'PET_TRANSPORTATION', 'PET_BOARDING', 'BUY', 'SELL', 'RENT', 'OFFER_RENT', 'BEAUTY', 'JOB1', 'JOB2', 'JOB3', 'JOB4');
ALTER TABLE "User" ALTER COLUMN "vehicleType" TYPE "VehicleType_new" USING ("vehicleType"::text::"VehicleType_new");
ALTER TABLE "Ride" ALTER COLUMN "vehicleType" TYPE "VehicleType_new" USING ("vehicleType"::text::"VehicleType_new");
ALTER TABLE "Vehicle" ALTER COLUMN "type" TYPE "VehicleType_new" USING ("type"::text::"VehicleType_new");
ALTER TYPE "VehicleType" RENAME TO "VehicleType_old";
ALTER TYPE "VehicleType_new" RENAME TO "VehicleType";
DROP TYPE "public"."VehicleType_old";
COMMIT;
